name: Deploy
on:
  push:
    branches:
      - main
    pull_request:
      - main

env:
  PROJECT_NAME: connected-sparta-python
  BK_NAME: project1-sparta
  APP_NAME: python-with-githubaction
  DEPLOY_GROUP: python-with-githubaction-group

jobs:
  build:
    name: Build, EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code.
        uses: actions/checkout@master

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
        #패키징 deploy.zip으로
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Transfer to EC2
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-northeast-2

      - name: Upload to S3
          run: aws s3 cp --region ap-northeast-2 deploy.zip s3://$BK_NAME/$PROJECT_NAME/deploy.zip

            - name: Code Deploy
              run: aws deploy create-deployment --application-name $APP_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $DEPLOY_GROUP --s3-location bucket=$BK_NAME,bundleType=zip,key=$PROJECT_NAME/deploy.zip
#      - name: Deploy to EB
#        uses: einaregilsson/beanstalk-deploy@v16
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          application_name: python-app
#          environment_name: Pythonapp-env
#          version_label: "python-${{ steps.format-time.outputs.replaced }}"
#          region: ap-northeast-2
#          deployment_package: deploy.zip